/*
 * 
 *
 */
package calculator;

import java.awt.Color;

public class Calculator extends javax.swing.JFrame {

    private double number1;
    private double number2;
    private String hold = "";
    private String type;
    private boolean plus;
    private boolean minus;
    private boolean multiply;
    private boolean divide;

    /**
     * Creates new form Calculator1
     */
    public Calculator() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        percentBtn = new javax.swing.JButton();
        bracketBtn1 = new javax.swing.JButton();
        bracketBtn2 = new javax.swing.JButton();
        acBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        displayTxtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        percentBtn.setBackground(new java.awt.Color(153, 153, 153));
        percentBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        percentBtn.setText("%");
        percentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentBtnActionPerformed(evt);
            }
        });

        bracketBtn1.setBackground(new java.awt.Color(153, 153, 153));
        bracketBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bracketBtn1.setText("(");
        bracketBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketBtn1ActionPerformed(evt);
            }
        });

        bracketBtn2.setBackground(new java.awt.Color(153, 153, 153));
        bracketBtn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bracketBtn2.setText(")");
        bracketBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracketBtn2ActionPerformed(evt);
            }
        });

        acBtn.setBackground(new java.awt.Color(153, 153, 153));
        acBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acBtn.setText("AC");
        acBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acBtnActionPerformed(evt);
            }
        });

        nineBtn.setBackground(new java.awt.Color(204, 204, 204));
        nineBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        sevenBtn.setBackground(new java.awt.Color(204, 204, 204));
        sevenBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        eightBtn.setBackground(new java.awt.Color(204, 204, 204));
        eightBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        divideBtn.setBackground(new java.awt.Color(153, 153, 153));
        divideBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        divideBtn.setText("÷");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        sixBtn.setBackground(new java.awt.Color(204, 204, 204));
        sixBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        fourBtn.setBackground(new java.awt.Color(204, 204, 204));
        fourBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fourBtn.setText("4");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        fiveBtn.setBackground(new java.awt.Color(204, 204, 204));
        fiveBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        multiplyBtn.setBackground(new java.awt.Color(153, 153, 153));
        multiplyBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        multiplyBtn.setText("×");
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });

        threeBtn.setBackground(new java.awt.Color(204, 204, 204));
        threeBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        oneBtn.setBackground(new java.awt.Color(204, 204, 204));
        oneBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        twoBtn.setBackground(new java.awt.Color(204, 204, 204));
        twoBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        minusBtn.setBackground(new java.awt.Color(153, 153, 153));
        minusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        minusBtn.setText("-");
        minusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtnActionPerformed(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(51, 153, 255));
        equalBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        equalBtn.setForeground(new java.awt.Color(255, 255, 255));
        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        zeroBtn.setBackground(new java.awt.Color(204, 204, 204));
        zeroBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        decimalBtn.setBackground(new java.awt.Color(204, 204, 204));
        decimalBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decimalBtn.setText(".");
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });

        plusBtn.setBackground(new java.awt.Color(153, 153, 153));
        plusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        displayTxtArea.setEditable(false);
        displayTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayTxtArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(decimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bracketBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bracketBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(percentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayTxtArea)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(displayTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentBtn)
                    .addComponent(bracketBtn1)
                    .addComponent(bracketBtn2)
                    .addComponent(acBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineBtn)
                    .addComponent(sevenBtn)
                    .addComponent(eightBtn)
                    .addComponent(divideBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixBtn)
                    .addComponent(fourBtn)
                    .addComponent(fiveBtn)
                    .addComponent(multiplyBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeBtn)
                    .addComponent(oneBtn)
                    .addComponent(twoBtn)
                    .addComponent(minusBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equalBtn)
                    .addComponent(zeroBtn)
                    .addComponent(decimalBtn)
                    .addComponent(plusBtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void percentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentBtnActionPerformed

    private void bracketBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracketBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bracketBtn1ActionPerformed

    private void bracketBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracketBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bracketBtn2ActionPerformed

    private void acBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acBtnActionPerformed
        hold = "";
        number1 = 0;
        number2 = 0;
        displayTxtArea.setText(hold);

    }//GEN-LAST:event_acBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        hold += "9";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_nineBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        hold += "7";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        hold += "8";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_eightBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        if (plus == false && minus == false && multiply == false) {
            hold += "÷";
            displayTxtArea.setText(hold);
            type = "divide";
            divide = true;
        }
    }//GEN-LAST:event_divideBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        hold += "6";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_sixBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        hold += "4";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        hold += "5";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        if (plus == false && minus == false && divide == false) {
            hold += "×";
            displayTxtArea.setText(hold);
            type = "multiply";
            multiply = true;
        }
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        hold += "3";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_threeBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        hold += "1";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        hold += "2";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_twoBtnActionPerformed

    private void minusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBtnActionPerformed
        if (plus == false && divide == false && multiply == false) {
            hold += "-";
            displayTxtArea.setText(hold);
            type = "subtract";
            minus = true;
        }
    }//GEN-LAST:event_minusBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        try {
            if (plus) {
                number1 = Double.parseDouble(hold.substring(0, hold.indexOf("+")));
                number2 = Double.parseDouble(hold.substring(hold.indexOf("+") + 1));
                hold = (number1 + number2) + "";
            } else if (minus) {
                number1 = Double.parseDouble(hold.substring(0, hold.indexOf("-")));
                number2 = Double.parseDouble(hold.substring(hold.indexOf("-") + 1));
                hold = (number1 - number2) + "";
            } else if (multiply) {
                number1 = Double.parseDouble(hold.substring(0, hold.indexOf("×")));
                number2 = Double.parseDouble(hold.substring(hold.indexOf("×")+ 1));
                hold = number1 * number2 + "";
            } else if (divide) {
                number1 = Double.parseDouble(hold.substring(0, hold.indexOf("÷")));
                number2 = Double.parseDouble(hold.substring(hold.indexOf("÷")+ 1));
                hold = number1 / number2 + "";
            } else {

            }
            displayTxtArea.setText(hold);
            resetConditions();
        } catch (NumberFormatException e) {
            hold = "";
            displayTxtArea.setText("Error");
        }


    }//GEN-LAST:event_equalBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        hold += "0";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
        hold += ".";
        displayTxtArea.setText(hold);
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        if (divide == false && minus == false && multiply == false) {
            hold += "+";
            displayTxtArea.setText(hold);
            type = "addition";
            plus = true;
        }
    }//GEN-LAST:event_plusBtnActionPerformed
    public void resetConditions() {
        plus = false;
        minus = false;
        multiply = false;
        divide = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acBtn;
    private javax.swing.JButton bracketBtn1;
    private javax.swing.JButton bracketBtn2;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JTextField displayTxtArea;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton percentBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
